name: Add Description To Release PR
run-name: Automatically add description to release PR
on:
  pull_request:
    types: [closed]
    branches:
      - release/*
jobs:
  add-description-to-release-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      BRANCH_NAME: ${{ github.base_ref }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: echo branch name
      run: echo $BRANCH_NAME
    - name: Check out repository code
      # NOTE: https://github.com/actions/checkout/releases/tag/v4
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        fetch-depth: 0
    - name: Setup ruby
      # NOTE: https://github.com/ruby/setup-ruby/releases/tag/v1.173.0
      uses: ruby/setup-ruby@5f19ec79cedfadb78ab837f95b87734d0003c899
      with:
        ruby-version: 3.1.0
    - name: Install git-pr-release
      run: gem install --no-document git-pr-release -v "2.2.0"
    - name: Prepare description template
      run: |
        RELEASE_DATE=$(echo $BRANCH_NAME | sed -e 's/release\///')
        echo "Release $RELEASE_DATE" > ./tmp/description.erb
        echo "<% pull_requests.each do |pr| -%>" >> ./tmp/description.erb
        echo "- #<%= pr.number %> <%= pr.mention %>" >> ./tmp/description.erb
        echo "<% end -%>" >> ./tmp/description.erb
    - run: git-pr-release
      env:
        GIT_PR_RELEASE_TOKEN: ${{ env.GITHUB_TOKEN }}
        GIT_PR_RELEASE_BRANCH_PRODUCTION: develop
        GIT_PR_RELEASE_BRANCH_STAGING: ${{ env.BRANCH_NAME }}
        GIT_PR_RELEASE_TEMPLATE: tmp/description.erb