name: Add Description To Release PR
run-name: Automatically add description to release PR
on:
  push:
  pull_request:
    branches:
      - release/*
jobs:
  add-description-to-release-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check out repository code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      with:
        fetch-depth: 0
    - name: Setup ruby
      uses: actions/setup-ruby@e932e7af67fc4a8fc77bd86b744acd4e42fe3543 # v1
      with:
        ruby-version: 2.6
    - name: Install git-pr-release
      run: gem install --no-document git-pr-release
    - name: Prepare description template
      run: |
        RELEASE_DATE=${{GITHUB_HEAD_REF##*/}}
        echo "Release $RELEASE_DATE" > /tmp/description.md
        echo "<% pull_requests.each do |pr| -%>" >> /tmp/description.md
        echo "<%=  pr.to_checklist_item %>" >> /tmp/description.md
        echo "<% end -%>" >> /tmp/description.md
    - run: git-pr-release
      env:
        GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_PR_RELEASE_BRANCH_PRODUCTION: develop
        GIT_PR_RELEASE_BRANCH_STAGING: ${{ GITHUB_HEAD_REF }}
        GIT_PR_RELEASE_TEMPLATE: /tmp/description.md