name: Create Release Branch
run-name: Automatically create release branch
# 月曜、水曜の18:00に実行（UTC9時）
on:
  schedule:
    - cron: '0 9 * * 1,3'
jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check out repository code
      # NOTE: https://github.com/actions/checkout/releases/tag/v4
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        fetch-depth: 0
    - name: Set Git config
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "Github Actions"
    - name: create and push release branch
      run: |
        git checkout develop
        # 8日後の日付をYYYYMMDDのフォーマットで取得
        RELEASE_DATE=$(date -d '8 days' '+%Y%m%d')
        git checkout -b release/$RELEASE_DATE
        git push origin release/$RELEASE_DATE
